mongodb:
  image: mongo:latest
  container_name: mongodb
  command: mongod --smallfiles
  ports:
   - "27017:27017"
  volumes:
   - ./mongo:/data/db:rw
  volume_driver: local
hygieia-api:
  image: hygieia-api:latest
  container_name: hygieia-api
  ports:
  - "8080:8080"
  volumes:
  - ./logs:/hygieia/logs
  links:
  - mongodb:mongo
hygieia-ui:
  image: hygieia-ui:latest
  container_name: hygieia-ui
  ports:
  - "8088:80"
  links:
  - hygieia-api

hygieia-jenkins-build-collector:
  image: hygieia-jenkins-build-collector:latest
  container_name: hygieia-jenkins-build
  volumes:
  - ./logs:/hygieia/logs
  links:
  - mongodb:mongo
  - hygieia-api
  environment:
#Jenkins server (required) - Can provide multiple
  - JENKINS_MASTER:-http://cdlmasjenkins0:8080/jenkins/view/Continuous_Builds/
#If using username/token for api authentication (required for Cloudbees Jenkins Ops Center) see sample
#  - JENKINS_OP_CENTER=http://username:token@jenkins.company.com
#Another option: If using same username/password Jenkins auth - set username/apiKey to use HTTP Basic Auth (blank=no auth)
#  - JENKINS_USERNAME
#  - JENKINS_API_KEY
  - JENKINS_CRON:-0 0/30 * * * *
#Determines if build console log is collected - defaults to false
#  - JENKINS_SAVE_LOG=true
hygieia-sonar-codequality-collector:
  image: hygieia-sonar-codequality-collector:latest
  container_name: hygieia-sonar-codequality
  volumes:
  - ./logs:/hygieia/logs
  links:
  - mongodb:mongo
  - hygieia-api
  environment:
  - SONAR_CRON:-0 0/5 * * * *
  - SONAR_URL:-http://cdlmasjenkins09.es.ad.adp.com:8080

hygieia-splunk-collector:
  image: hygieia-splunk-collector:latest
  container_name: hygieia-splunk
  volumes:
  - ./logs:/hygieia/logs
  links:
  - mongodb:mongo
  - hygieia-api
  environment:
  - SPLUNK_CRON:-0 0/15 * * * *
  - SPLUNK_USERNAME:-kasibhov
  - SPLUNK_PASSWORD:-Krishna@11
  - SPLUNK_URI:-splunkcdl.es.ad.adp.com
  - SPLUNK_APP:-wfn_pw
  - SPLUNK_SAVEDSEARCH:-HygieiaWFN


hygieia-subversion-scm-collector:
  image: hygieia-subversion-scm-collector:latest
  container_name: hygieia-subversion
  volumes:
  - ./logs:/hygieia/logs
  links:
  - mongodb:mongo
  - hygieia-api
  environment:
  - SUBVERSION_CRON:-0 0/5 * * * *

#Shared subversion username and password
  - SUBVERSION_USERNAME:-build
  - SUBVERSION_PASSWORD:-BDSbds@123

#Maximum number of days to go back in time when fetching commits
  - SUBVERSION_COMMIT_THRESHOLD_DAYS:-15
  - SUBVERSION_URL:-http://svn-mas.es.oneadp.com/svn/MAS_WFN/
#
hygieia-versionone-collector:
  image: hygieia-versionone-collector:latest
  container_name: hygieia-versionone
  volumes:
  - ./logs:/hygieia/logs
  links:
  - mongodb:mongo
  - hygieia-api
  environment:
#Page size for data calls (VersionOne recommended 2000)
  - VERSIONONE_PAGE_SIZE:-2000
#Proxy assumes a host:port syntax
#  - VERSIONONE_PROXY_URL=""
  - VERSIONONE_URL:-http://rally1.rallydev.com
#Access token provided by VersionOne
  - VERSIONONE_ACCESS_TOKEN:-_kB9hwWTSd5tVvzHKeoY1SvTINUPYsZ7s7DGw2V0
  - VERSIONONE_PROJECT_ID:-9105435711
  - VERSIONONE_APP_NAME:-WFN
#In-built folder housing prepared REST queries (required)
#  - VERSIONONE_QUERY_FOLDER=v1api-queries

#Jira API Query file names (String template requires the files to have .st extension) (required)
#  - VERSIONONE_STORY_QUERY=story
#  - VERSIONONE_EPIC_QUERY=epicinfo
#  - VERSIONONE_PROJECT_QUERY=projectinfo
#  - VERSIONONE_MEMBBER_QUERY=memberinfo
#  - VERSIONONE_SPRINT_QUERY=sprintinfo
#  - VERSIONONE_TEAM_QUERY=teaminfo
#  - VERSIONONE_TRENDING_QUERY=trendinginfo

# Trending Query:  Number of days in a sprint (not-required)
#  - VERSIONONE_SPRINT_DAYS=60
# Trending Query:  Length of sprint week (not-required)
#  - VERSIONONE_SPRINT_END_PRIOR=7

#Scheduled Job prior minutes to recover data created during execution time (usually, 2 minutes is enough)
#  - VERSIONONE_SCHEDULED_PRIOR_MIN=2

#Delta change date that modulates the collector item task - should be about as far back as possible, in ISO format (required)
#  - VERSIONONE_DELTA_COLLECTORITEM_START_DATE=2008-01-01T00:00:00.000000

#VersionOne Connection Details



#Start dates from which to begin collector data, if no other data is present - usually, a month back is appropriate (required)
#  - VERSIONONE_DELTA_START_DATE=2015-03-01T00:00:00.000000
#  - VERSIONONE_MASTER_START_DATE=2008-01-01T00:00:00.000000

hygieia-udeploy-collector:
  image: hygieia-udeploy-collector:latest
  container_name: hygieia-udeploy
  volumes:
  - ./logs:/hygieia/logs
  links:
  - mongodb:mongo
  - hygieia-api
  environment:
#UDeploy server (required) - Can provide multiple
  - UDEPLOY_URL:-http://cdlorchestration.nj.adp.com/oo/
#UDeploy user name (required)
  - UDEPLOY_USERNAME:-build
#UDeploy password (required)
  - UDEPLOY_PASSWORD:-BDSbds@123
#Collector schedule (required)
  - UDEPLOY_CRON:-0 0/60 * * * *
